# Site settings 配置站点
title: 'BerryQiu的妙妙屋'
description: '这里是BerryQiu的妙妙屋'
keywords: 'blog, cs'
url: 'https://qiutongxue.github.io' # your host
baseurl: '/'
# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: Berry Qiu
# name: 'your awesome name'
name: 'Berry Qiu'
# NickName: 'your awesome nickname'
NickName: '萌德LR'
# webtitle: 'your awesome webtitle'
webtitle: 'BerryQiu的妙妙屋'
# bio: 'your awesome bio' # 个人经历
bio: '三五知己，谈笑风生'
about: true
# aboutyou: 'your introduction'
aboutyou: '大家好，欢迎来到我的个人博客，可以通过下方的渠道和我交流~'
portraits: '/assets/profile.jpg' # your portraits image file path

# 图标库（iconfont）
icon-source: '//at.alicdn.com/t/font_1568694_x0y0izdqw9i.css'
total-words-before: '<i class="iconfont icon-text"></i>'    #文章字数前缀
total-words-after: '字'       #文章字数后缀
time-to-read-before: '<i class="iconfont icon-time"></i>'     #预计阅读时间前缀
time-to-read-after: '分钟'    #预计阅读时间后缀
post-pv-before: '<i class="iconfont icon-view"></i>'        #浏览量前缀
post-pv-after: ''       #浏览量后缀
emoji: '<i class="iconfont icon-emoji"></i>'

# SNS
SNS: true
# SNS图标地址（iconfont）
SNS-source: '//at.alicdn.com/t/font_1563017_y8qm55gi2oa.js'
SNS-icon: #['weibo', 'qq', 'github', 'weixin', 'codepen', 'bilibili', 'bilitv','neteaseCloudMusic','Facebook','instagram', ]
  mail: '###'
  weixin: '###' # 你的微信二维码存放的地址
  qq: '###' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/qiutongxue'
  bilibili: 'https://space.bilibili.com'
  weibo: 'https://weibo.com/'
  neteaseCloudMusic: 'https://music.163.com/#/user/home?id=269757591'
  zhihu: 'https://www.zhihu.com/'
  steam: 'https://steamcommunity.com/'
  gitee: 'http://qiutongxue.gitee.io/'
  # RSS: '/feed.xml'
  # bilitv: '' #小电视形态
  # instagram: ''
  # Twitter: ''
  # Facebook: ''
  # google: ''
  # linkedin: ''
  # lofter: ''
  # codepen: ''


social_mail:
  gmail: 'xqiutongxue@gmail.com'
  outlook: 'qiutongxue@outlook.com'
  foxmail: 'xqiutongxue@foxmail.com'
SNS-qrcode:
  weixin: true
  qq: true

  # 分页
paginate: 10
paginatepath: ['page:num']

# 引入Mathjax
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

  # since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'friendly'

# 友情链接
friends:
  Jekyll: 'https://www.jekyll.com.cn/'
  犊马不识途: 'http://dumabushitu.github.io'
  Liquid中文文档: 'https://liquid.bootcss.com/'
  xukiseven: 'https://github.com/xukimseven/HardCandy-Jekyll'
  Vssue: https://vssue.js.org/zh/
  Iconfont: https://www.iconfont.cn/

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
comments:
  enable: true  # 是否使用评论
  # disqus 评论
  disqus: 
    enable: false
    disqus_url: '' # https://abc.disqus.com/embed.js
  # 来必力评论
  livere: 
    enable: false
    livere_uid: '' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
  Gitment: 
    enable: false
    Gitment_owner: 'qiutongxue'  # github用户名
    Gitment_repo: 'qiutongxue.github.io'  # github博客存放的仓库名
    client_id: '05284778ce91bf83f1bf'  # 注册 OAuth Application 后获得的 client_id
    client_secret: '479b8271851db1055103d3edef0beaedc00ad644'  # 注册 OAuth Application 后获得的 client_secret
#Vssue评论，也是OAuth Application，相应配置与Gitment相同，就不赘述了
  vssue: 
    enable: false
    type: 'github' # 可用： github、gitee
    # 如果抽取出来。下面两个中只保留一个
    # 下面是github配置
    Github_owner: 'qiutongxue'  # github用户名
    Github_repo: 'qiutongxue.github.io'  # github博客存放的仓库名
    client_id: '05284778ce91bf83f1bf'  # 注册 OAuth Application 后获得的 client_id
    client_secret: '479b8271851db1055103d3edef0beaedc00ad644'  # 注册 OAuth Application 后获得的 client_secret
    # gitee的配置
    Gitee_owner: 'qiutongxue'
    Gitee_repo: 'comments-repository'
    Gitee_client_id: '38a30648559e1a52ba71d90691e64a296b509615796884b7e97abb78b0bb4e6a'
    Gitee_client_secret: '6755c77c8a4cc2cc0e223051aa7ff50bcbb9a29e04a8dd60cc43958ebf8b3fa9'
  
  valine:
    enable: true
    appId: DABE2iYCIJ9y6PQ0ffnfkIug-gzGzoHsz
    appKey: XCYilVAul18HQgTyghVbAWXl

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: false
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: '14f04824ed9083b506084e7cd179df1b'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

#开启颜色跟踪（与文章相关的组件与文章主题颜色绑定）
color-bind:
  index: false    # false时默认为灰色
  timeline: true  # fasle时默认为紫色
  tags: true      # false时默认按顺序： 蓝-紫-红-黄
  comments: true  # false时默认为浅绿色(Vssue)
# 颜色库，博客文章的背景颜色根据【index = 字数 modulo 库颜色数量】从中获取相应的颜色，十六进制颜色需要用【双引号】包裹

  
search: true
  

exclude:
  - .post-template
  - README.md
  - LICENSE
