# Site settings 配置站点
title: 'your awesome title'
description: 'your web description'
keywords: 'your web keywords, another keywords'
url: 'https://abc.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
# name: 'your awesome name'
name: 'Berry Qiu'
# NickName: 'your awesome nickname'
NickName: '萌德LR'
# webtitle: 'your awesome webtitle'
webtitle: 'QiuBerry的妙妙屋'
# bio: 'your awesome bio' # 个人经历
bio: '来自福建厦门，四川大学机械设计制造及其自动化专业本科在读'
about: true
# aboutyou: 'your introduction'
aboutyou: '三五知己，谈笑风生'
portraits: '/assets/profile.jpg' # your portraits image file path

# SNS
SNS: true
# SNS图标地址（iconfont阿里图标）
SNS-source: '//at.alicdn.com/t/font_1563017_g1zlhj4y9b.js'
SNS-icon: #['Facebook', 'weibo', 'qq', 'github','Twitter', 'instagram', 'weixin', 'codepen', 'bilibili', 'bilitv','neteaseCloudMusic']
  mail: ''
  weixin: '' # 你的微信二维码存放的地址
  qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: ''
  bilibili: ''
  #bilitv: '' #小电视形态
  weibo: ''
  instagram: ''
  Twitter: ''
  Facebook: ''
  google: ''
  neteaseCloudMusic: ''
  zhihu: ''
  linkedin: ''
  lofter: ''
  codepen: ''

# 分页
paginate: 5
paginatepath: ['page:num']

# since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: '' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: '14f04824ed9083b506084e7cd179df1b'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）,可用十六进制表示#F7F7F7
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)

exclude:
  - .post-template
  - README.md
  - LICENSE
