# Site settings 配置站点
title: 'BerryQiu的妙妙屋'
description: '这里是BerryQiu的妙妙屋'
keywords: 'blog, cs'
url: 'https://qiutongxue.github.io' # your host
baseurl: '/'
# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: Berry Qiu
# name: 'your awesome name'
name: 'Berry Qiu'
# NickName: 'your awesome nickname'
NickName: '萌德LR'
# webtitle: 'your awesome webtitle'
webtitle: 'QiuBerry的妙妙屋'
# bio: 'your awesome bio' # 个人经历
bio: '三五知己，谈笑风生'
about: true
# aboutyou: 'your introduction'
aboutyou: '大家好，欢迎来到我的个人博客，可以通过下方的渠道和我交流~'
portraits: '/assets/profile.jpg' # your portraits image file path

# SNS
SNS: true
# SNS图标地址（iconfont阿里图标）
SNS-source: '//at.alicdn.com/t/font_1563017_c9npfhfwibm.js'
SNS-icon: #['weibo', 'qq', 'github', 'weixin', 'codepen', 'bilibili', 'bilitv','neteaseCloudMusic','Facebook','instagram', ]
  mail: '###'
  weixin: '###' # 你的微信二维码存放的地址
  qq: '###' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/qiutongxue'
  bilibili: 'https://space.bilibili.com/3995868'
  weibo: 'https://weibo.com/u/5899574062'
  neteaseCloudMusic: 'https://music.163.com/#/user/home?id=269757591'
  zhihu: 'https://www.zhihu.com/people/qiu-bo-wei-79/activities'
  steam: 'https://steamcommunity.com/id/994702889/'
  RSS: '/feed.xml'
  # bilitv: '' #小电视形态
  # instagram: ''
  # Twitter: ''
  # Facebook: ''
  # google: ''
  # linkedin: ''
  # lofter: ''
  # codepen: ''
social_mail:
  gmail: 'xqiutongxue@gmail.com'
  outlook: 'qiutongxue@outlook.com'
  foxmail: 'xqiutongxue@foxmail.com'
SNS-qrcode:
  weixin: true
  qq: true
# 分页
paginate: 5
paginatepath: ['page:num']

# since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'friendly'

# 友情链接
friends:
  Jekyll: 'https://www.jekyll.com.cn/'
  犊马不识途: 'http://dumabushitu.github.io'
  Liquid中文文档: 'https://liquid.bootcss.com/'
  xukiseven: 'https://github.com/xukimseven/HardCandy-Jekyll'
  Vssue: https://vssue.js.org/zh/

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: '' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: true
#Vssue评论，也是OAuth Application，相应配置与Gitment相同，就不赘述了
vssue: false
# 下面是Gitment和Vssue的配置 （Vssue和Gitment只能二选一）
Gitment_owner: 'qiutongxue'  # github用户名
Gitment_repo: 'qiutongxue.github.io'  # github博客存放的仓库名
client_id: '05284778ce91bf83f1bf'  # 注册 OAuth Application 后获得的 client_id
client_secret: '479b8271851db1055103d3edef0beaedc00ad644'  # 注册 OAuth Application 后获得的 client_secret




# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: '14f04824ed9083b506084e7cd179df1b'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

#开启颜色跟踪（与文章相关的组件与文章背景色绑定）
color-bind:
  index: false
  timeline: true
  tags: true
# 颜色库，博客文章的背景颜色根据【index = 字数 modulo 库颜色数量】从中获取相应的颜色，十六进制颜色需要用【双引号】包裹
page-color: 
  - "#9A85FF"  #紫
  - "#FF5A5A"  #红
  - "#FFD220"  #黄
  - "#62AAFF"  #蓝
  - "#78D2F1"  #蓝
  - "#00E673"  #绿
  - "#FF9F38"  #橙
  - "#FF99CB"  #粉红
  - "#BA99FF"  #紫
  - "#9A9A9A"  #灰
  - "#46E595"  #绿
  - "#FF6200"  #橙红
  - "#FF9700"  #橙
  - "#FB7299"  #Bilibili粉
  - "#20E3C9"  #青色
  

  

exclude:
  - .post-template
  - README.md
  - LICENSE
